import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import BookList from '../components/BookList/booklist'
import { BASE_URL } from '../constants/constants'
import styles from '../styles/Home.module.css'

interface PageProps {
  bookData: Array<Book>
}

const Home: NextPage<PageProps> = ({ bookData }) => {

  const [ formOpen, setFormOpen ] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Bookshelf</title>
        <meta name="description" content="Generated by create next app && @smromain" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <BookList books={bookData} setFormOpen={setFormOpen} />
      </>
    </div>
  )
}

export async function getServerSideProps() {

  const res = await fetch(
    `${BASE_URL}/books`,
    {
      method: 'GET',
      headers: new Headers({
        'Authorization': 'steveromain'
      })
    }
  )

  const bookData: Array<Book> = await res.json()

  return { props: { bookData }}

}

export default Home
