import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import BookList from '../components/BookList/booklist'
import BookForm from '../components/BookForm/bookform'
import { BASE_URL } from '../constants/constants'
import styles from '../styles/Home.module.css'

interface PageProps {
  initialBookData: Array<Book>
}

const Home: NextPage<PageProps> = ({ initialBookData = [] }) => {

  const [ formOpen, setFormOpen ] = useState(false)
  const [ bookData, setBookData ] = useState(initialBookData)

  return (
    <div className={styles.container}>
      <Head>
        <title>Bookshelf</title>
        <meta name="description" content="Generated by create next app && @smromain" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        { formOpen ? (
          <BookForm 
            setFormOpen={setFormOpen}
            setBookData={setBookData}
          />
        ) : ( 
          <BookList
            books={bookData}
            setFormOpen={setFormOpen}
            setBookData={setBookData}
          />
        )}
      </>
    </div>
  )
}

export async function getServerSideProps() {

  const res = await fetch(
    `${BASE_URL}/books`,
    {
      method: 'GET',
      headers: new Headers({
        'Authorization': 'steveromain'
      })
    }
  )

  const initialBookData: Array<Book> = await res.json()

  return { props: { initialBookData }}

}

export default Home
